// <auto-generated />
namespace BorsaBekya.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IDENTITY_INSERTOnIntblUsser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IDENTITY_INSERTOnIntblUsser));
        
        string IMigrationMetadata.Id
        {
            get { return "201804302333241_IDENTITY_INSERTOnIntblUsser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
